config/routes.rb
Rails.application.routes.draw do
  get 'how_it_works/index'

	devise_scope :user do
  	devise_for :users
  end

  root to: 'phrases#index'
  
  resources :phrases do
    resources :phrase_collabs, only: [:new]
  end

  
end

app/models/phrase.rb
class Phrase < ActiveRecord::Base
  has_many :phrase_collabs, class_name: 'Phrase'
  belongs_to :phrase, foreign_key: 'parent_id'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	layout :layout_by_resource
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def after_sign_in_path_for(resources)
  	phrases_path
  end

  def layout_by_resource
  	devise_controller? ? "sign_in" : "application"
  end
end

app/controllers/how_it_works_controller.rb
class HowItWorksController < ApplicationController
  def index
  end
end

app/controllers/phrase_collabs_controller.rb
class PhraseCollabsController < ApplicationController
  before_action :set_phrase, only: [:show, :edit, :update, :destroy]

  def new
    @phrase_collab = Phrase.new
  end

  private

  def set_phrase
    @phrase = Phrase.find params[:phrase_id]
  end
end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
  def index
    @phrases = Phrase.all
  end

  def new
  	@phrase = Phrase.new
  end

  def create
  	@phrase = Phrase.create text: params[:phrase][:text]
  	@phrase.user_id = current_user.id
  	@phrase.save
  	redirect_to root_path, notice: 'Phrase was successfully created.'
  end

  def destroy
  	Phrase.find_by_id(params[:id]).destroy
  	redirect_to root_path, notice: 'Phrase was successfully deleted.'
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/how_it_works_helper.rb
module HowItWorksHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/views/how_it_works/index.html.slim
h1 HowItWorks

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
li
  == link_to 'How It Works', how_it_works_index_path	
li  
  == link_to 'Sign Out', destroy_user_session_path

app/views/layouts/_navigation_tabs.html.slim
ul.nav.nav-tabs
  li = link_to 'Phrases', phrases_path, role: 'presentation' 
  li = link_to 'Sentences', "#", role: 'presentation' 
  li = link_to 'Paragraphs', "#", role: 'presentation' 
  li = link_to 'Top Stories', "#", role: 'presentation' 

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Collaborative Short Stories'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Collaborative Short Stories'}"
    == stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    .container
      == render 'layouts/messages'
      == render 'layouts/navigation_tabs'
      == yield

app/views/layouts/sign_in.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Collaborative Short Stories'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Collaborative Short Stories'}"
    == stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
    br
    .container
      == render 'layouts/messages'
      == yield

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/phrase_collabs/new.html.slim
== form_for @phrase_collab do |f|
  == f.text_field :text
  == f.submit

app/views/phrases/_form.html.slim
= form_for @phrase do |f|
  - if @phrase.errors.any?
    #error_explanation
      h2 = "#{pluralize(@phrase.errors.count, "error")} prohibited this phrase from being saved:"
      ul
        - @phrase.errors.full_messages.each do |message|
          li = message
  .field
    = f.label :text
    = f.text_field :text
  .field
    = f.hidden_field :parent_id
  .field
    = f.label :child_count
    = f.number_field :child_count
  .field
    = f.label :match_count
    = f.number_field :match_count
  .actions = f.submit

app/views/phrases/_phrase.html.slim
li.phrase
  .well
    .row
      .col-sm-10	
        == phrase.text
      .col-sm-1
        == link_to 'Add', new_phrase_phrase_collab_path(phrase)
      .col-sm-1
        == link_to "Delete",phrase_path(phrase), method: :delete

app/views/phrases/edit.html.slim
h1 Editing phrase

== render 'form'

= link_to 'Show', @phrase
'|
= link_to 'Back', phrases_path

app/views/phrases/index.html.slim
#callouts.row
  .col-sm-6
    .alert.alert-info
      |
        Contribute to the budding short stories below
  .col-sm-6
    .alert.alert-info.clearfix
      .pull-left Or start your own...
      .pull-right
        == link_to 'Go', new_phrase_path

.row
  .col-sm-12
    ul.list-unstyled
      == render @phrases

app/views/phrases/new.html.slim
h1 New phrase

== render 'form'

= link_to 'Back', phrases_path

app/views/phrases/show.html.slim
p#notice = notice

p
  strong Text:
  = @phrase.text
p
  strong Parent:
  = @phrase.parent_id
p
  strong Child count:
  = @phrase.child_count
p
  strong Match count:
  = @phrase.match_count

= link_to 'Edit', edit_phrase_path(@phrase)
'|
= link_to 'Back', phrases_path

app/views/visitors/index.html.erb
<h3>Welcome</h3>